import React from 'react';
import { Link } from 'react-router-dom';
import { useHLDDayState } from '../../../hooks/usePersistedState';
import '../../HLDDay.css';
import '../ArticleContent.css';

function Week1Day3() {
  const weekNum = 1, dayNum = 3, topic = "Mid-Week Practice", concepts = "Practice quiz on Days 1-2 concepts";
  
  const {
    activeTab, setActiveTab,
    sidebarCollapsed, setSidebarCollapsed,
    mobileMenuOpen, setMobileMenuOpen,
    selectedAnswers, setSelectedAnswers,
    showResults, setShowResults,
    currentQuestionIndex, setCurrentQuestionIndex,
    resetQuiz
  } = useHLDDayState(weekNum, dayNum);
  const tabs = [{ id: 'video', label: 'Video Lesson', icon: '🎬', available: false, color: '#E91E63' },{ id: 'article', label: 'Reading Material', icon: '📖', available: true, color: '#2196F3' },{ id: 'quiz', label: 'Practice Quiz', icon: '✅', available: true, color: '#9C27B0' },{ id: 'assignment', label: 'Assignment', icon: '📝', available: false, color: '#FF9800' }];

  const quizQuestions = [
    { id: 1, question: "What does HLD focus on?", options: ["Code implementation", "System architecture and components", "Unit tests", "Variable naming"], correct: 1, explanation: "HLD focuses on overall system architecture and component interactions." },
    { id: 2, question: "Which is a functional requirement?", options: ["99.9% uptime", "Response < 100ms", "User login", "Handle 1M users"], correct: 2, explanation: "Functional requirements describe features - what the system does." },
    { id: 3, question: "What does '99.99%' availability mean?", options: ["3.65 days downtime/year", "8.76 hours downtime/year", "52.6 minutes downtime/year", "5.26 minutes downtime/year"], correct: 2, explanation: "4 nines (99.99%) = ~52.6 minutes downtime per year." },
    { id: 4, question: "In MoSCoW, what does 'M' stand for?", options: ["Maybe have", "Must have", "Might have", "More than have"], correct: 1, explanation: "M = Must have - critical features without which system fails." },
    { id: 5, question: "Which is NOT a system component?", options: ["Load Balancer", "Database", "CSS stylesheet", "Message Queue"], correct: 2, explanation: "CSS is a frontend styling concern, not a system architecture component." },
    { id: 6, question: "What is the correct design flow?", options: ["LLD → HLD → Requirements", "Requirements → HLD → LLD", "HLD → Requirements → LLD", "LLD → Requirements → HLD"], correct: 1, explanation: "Correct flow: Requirements → HLD (architecture) → LLD (detailed design)." },
    { id: 7, question: "Latency requirement example?", options: ["Store 1TB", "Support 1M users", "Response < 200ms", "99.9% uptime"], correct: 2, explanation: "Latency measures response time - how fast the system responds." },
    { id: 8, question: "What does a Load Balancer do?", options: ["Store data", "Distribute traffic across servers", "Cache content", "Encrypt data"], correct: 1, explanation: "Load balancers distribute incoming traffic across multiple servers." }
  ];

  const handleAnswerSelect = (qId, idx) => setSelectedAnswers(p => ({ ...p, [qId]: idx }));
  const renderArticleContent = () => (<div className="content-panel article-panel"><article className="article-container"><header className="article-header"><h1>Week 1 Review: Days 1-2</h1></header><div className="article-content"><h2 className="md-h2">Day 1: System Design Basics</h2><ul><li>HLD: System architecture, components, data flow</li><li>LLD: Detailed design, classes, schemas</li><li>Key components: Load Balancer, Web/App Servers, Database, Cache, CDN</li></ul><h2 className="md-h2">Day 2: Requirements</h2><ul><li>Functional: WHAT the system does (features)</li><li>Non-functional: HOW the system performs (quality)</li><li>NFR categories: Performance, Scalability, Availability, Security</li><li>MoSCoW: Must/Should/Could/Won't have</li></ul></div></article></div>);
  
  const renderQuizContent = () => {
    const total = quizQuestions.length, curr = quizQuestions[currentQuestionIndex], answered = Object.keys(selectedAnswers).length;
    if (showResults) { const score = quizQuestions.filter(q => selectedAnswers[q.id] === q.correct).length; return (<div className="content-panel quiz-panel"><div className="quiz-container"><div className="quiz-results"><div className="results-header"><h2>Quiz Complete!</h2><div className="score-circle"><span className="score-value">{Math.round((score/total)*100)}%</span><span className="score-label">Score</span></div></div><div className="results-review"><h3>Review</h3>{quizQuestions.map((q,i)=>(<div key={q.id} className={`review-item ${selectedAnswers[q.id]===q.correct?'correct':'incorrect'}`}><div className="review-header"><span className="review-number">Q{i+1}</span><span className={`review-badge ${selectedAnswers[q.id]===q.correct?'correct':'incorrect'}`}>{selectedAnswers[q.id]===q.correct?'✓':'✗'}</span></div><p className="review-question">{q.question}</p><div className="review-answers"><p><strong>Your answer:</strong> {q.options[selectedAnswers[q.id]]||'None'}</p>{selectedAnswers[q.id]!==q.correct&&<p><strong>Correct:</strong> {q.options[q.correct]}</p>}</div><div className="explanation">{q.explanation}</div></div>))}</div><div className="results-actions"><button className="retry-btn" onClick={()=>{setSelectedAnswers({});setShowResults(false);setCurrentQuestionIndex(0);}}>Retry</button></div></div></div></div>); }
    return (<div className="content-panel quiz-panel"><div className="quiz-container"><header className="quiz-header"><h1>Mid-Week Practice Quiz</h1><div className="quiz-stats"><div className="stat-card"><span className="stat-value">{total}</span><span className="stat-label">Questions</span></div></div></header><div className="quiz-progress"><div className="progress-text">Question {currentQuestionIndex+1} of {total}</div><div className="progress-bar"><div className="progress-fill" style={{width:`${((currentQuestionIndex+1)/total)*100}%`}}></div></div></div><div className="quiz-question-single"><div className="question-card"><div className="question-header"><span className="question-number">Q{currentQuestionIndex+1}</span></div><p className="question-text">{curr.question}</p><div className="options-list">{curr.options.map((o,i)=>(<label key={i} className={`option-item ${selectedAnswers[curr.id]===i?'selected':''}`}><input type="radio" checked={selectedAnswers[curr.id]===i} onChange={()=>handleAnswerSelect(curr.id,i)}/><span className="option-letter">{String.fromCharCode(65+i)}</span><span className="option-text">{o}</span></label>))}</div></div></div><div className="quiz-navigation"><button className="nav-btn prev" disabled={currentQuestionIndex===0} onClick={()=>setCurrentQuestionIndex(i=>i-1)}>&lt;&lt; Prev</button><div className="question-dots">{quizQuestions.map((q,i)=>(<button key={i} className={`dot ${i===currentQuestionIndex?'active':''} ${selectedAnswers[q.id]!==undefined?'answered':''}`} onClick={()=>setCurrentQuestionIndex(i)}>{i+1}</button>))}</div>{currentQuestionIndex===total-1?<button className="nav-btn submit" onClick={()=>setShowResults(true)}>Submit</button>:<button className="nav-btn next" onClick={()=>setCurrentQuestionIndex(i=>i+1)}>Next &gt;&gt;</button>}</div></div></div>);
  };

  const renderEmptyState = (icon, title) => (<div className="content-panel"><div className="empty-state"><div className="empty-icon">{icon}</div><h3>{title}</h3><p>Not available for practice days.</p></div></div>);

  return (
    <div className="hld-day-layout">
      <div className="mobile-header"><Link to="/hld" className="mobile-back-link">&lt;&lt; Back</Link><div className="mobile-title"><span className="mobile-week-badge">W{weekNum}D{dayNum}</span><span className="mobile-topic">{topic}</span></div><button className="mobile-menu-btn" onClick={()=>setMobileMenuOpen(!mobileMenuOpen)}><span className={`hamburger ${mobileMenuOpen?'open':''}`}></span></button></div>
      <div className={`mobile-menu-overlay ${mobileMenuOpen?'open':''}`} onClick={()=>setMobileMenuOpen(false)}></div>
      <div className={`mobile-menu ${mobileMenuOpen?'open':''}`}><div className="mobile-menu-header"><div className="mobile-menu-info"><div className="week-badge">Week {weekNum} • Day {dayNum}</div><h3>{topic}</h3></div></div><nav className="mobile-menu-nav">{tabs.map(t=>(<button key={t.id} className={`mobile-nav-item ${activeTab===t.id?'active':''} ${!t.available?'disabled':''}`} onClick={()=>{if(t.available){setActiveTab(t.id);setMobileMenuOpen(false);}}} style={{'--tab-color':t.color}}><span className="nav-icon">{t.icon}</span><span className="nav-label">{t.label}</span></button>))}</nav><div className="mobile-menu-footer"><div className="mobile-day-nav"><Link to="/hld/week/1/day/2" className="nav-link prev">&lt;&lt; Day 2</Link><Link to="/hld/week/1/day/4" className="nav-link next">Day 4 &gt;&gt;</Link></div></div></div>
      <aside className={`sidebar ${sidebarCollapsed?'collapsed':''}`}><div className="sidebar-header"><Link to="/hld" className="back-link"><span className="back-icon">&lt;&lt;</span>{!sidebarCollapsed&&<span>Back to Course</span>}</Link><button className="collapse-btn" onClick={()=>setSidebarCollapsed(!sidebarCollapsed)}>{sidebarCollapsed?'>>':'<<'}</button></div>{!sidebarCollapsed&&<div className="sidebar-info"><div className="week-badge">Week {weekNum} • Day {dayNum}</div><h2 className="day-topic">{topic}</h2><p className="day-concepts">{concepts}</p></div>}<nav className="sidebar-nav">{tabs.map(t=>(<button key={t.id} className={`nav-item ${activeTab===t.id?'active':''} ${!t.available?'disabled':''}`} onClick={()=>t.available&&setActiveTab(t.id)} style={{'--tab-color':t.color}}><span className="nav-icon">{t.icon}</span>{!sidebarCollapsed&&<><span className="nav-label">{t.label}</span>{t.available&&<span className="nav-count">1</span>}</>}</button>))}</nav>{!sidebarCollapsed&&<div className="sidebar-footer"><div className="day-navigation"><Link to="/hld/week/1/day/2" className="nav-link prev">&lt;&lt; Day 2</Link><Link to="/hld/week/1/day/4" className="nav-link next">Day 4 &gt;&gt;</Link></div></div>}</aside>
      <main className="main-content"><header className="content-header"><div className="header-left"><span className="content-type" style={{'--type-color':tabs.find(t=>t.id===activeTab)?.color}}>{tabs.find(t=>t.id===activeTab)?.icon} {tabs.find(t=>t.id===activeTab)?.label}</span></div><div className="header-right"><span className="progress-indicator">Week {weekNum}, Day {dayNum}</span></div></header><div className="content-body">{activeTab==='video'&&renderEmptyState('🎬','Video Not Available')}{activeTab==='article'&&renderArticleContent()}{activeTab==='quiz'&&renderQuizContent()}{activeTab==='assignment'&&renderEmptyState('📝','Assignment Not Available')}</div></main>
    </div>
  );
}

export default Week1Day3;
